var arrLang = {
    'en': {
        'Itme_HOME': 'HOME',
        'Itme_PROFILE': 'PROFILE',
        'Itme_SKILLS': 'SKILLS',
        'Itme_PORTFOLIO': 'PORTFOLIO',
        'Itme_CONTACT': 'CONTACT',
        'PROFILE_Hi': 'Hi! I\'m Kevin Lin.',
        'PROFILE_Saying': 'Let\'s make a better design for the product.',
        'PROFILE_About_title': 'ABOUT ME',
        'PROFILE_Education_title': 'Education',
        'PROFILE_Experience_title': 'Experience',
        'PROFILE_Education1': ' • Da-Yeh University CSIE.',
        'PROFILE_AboutMe': 'Since I started working on programming, I liked programming, and even when I was working, I liked to write code. I also learned the front-end and back-end programming languages and tried to be a full-end engineer, but I prefer front-end design. In addition to programming, I like to paint and even start to learn art design. I like reasoning. Whether it is a novel or a puzzle, my friends have said that I am good at logical reasoning.',
        'RESUME_Experience_1': ' • Jabil Green Point(Full Stack Developer). Jul 2015-Jun 2016',
        'RESUME_Experience_2': ' • Jabil Green Point(Full Stack Developer). Jul 2016-Nov 2016',
        'RESUME_Experience_3': ' • R.O.C. Army Dec 2016-Mar 2017',
        'RESUME_Experience_4': ' • Jabil Green Point(Full Stack Developer). Apr 2017-Present',
        'SKILLS_frontend': 'Front End',
        'SKILLS_backend': 'Back End',
        'SKILLS_others': 'Others',
        'SKILLS_frontend_content_1': 'HTML5/CSS/LESS.',
        'SKILLS_frontend_content_2': 'Javascript/JQuery/Vue.js.',
        'SKILLS_frontend_content_3': ' • Familiar with CSS,JS,JQuery, and created package.Understand Vue.js, Less.',
        'SKILLS_frontend_content_4': ' • Familiar with design layout, using Web APIs, RWD, i18n.',
        'SKILLS_frontend_content_5': ' • With the concept of performance optimization, user experience (UX).',
        'SKILLS_frontend_content_6': ' • Let MES RWD,multilingual and performance optimization in the "Green Point"(Web initial load time from 3778 ms to 1279 ms).',
        'SKILLS_frontend_content_7': ' • Has nearly three years of full-end development experience.',
        'SKILLS_backend_content_1': 'ASP.NET MVC(C#).',
        'SKILLS_backend_content_2': 'Golang.',
        'SKILLS_backend_content_3': ' • Has the ability to concatenate databases and develop Web APIs.',
        'SKILLS_backend_content_4': ' • Has OOP and setting server concept.',
        'SKILLS_backend_content_5': ' • Developing PLC control program with KEYENCE library in the "Green Point".',
        'SKILLS_backend_content_6': ' • Has nearly three years of full-end development experience.',
        'SKILLS_others_content_1': 'Git/SVN。',
        'SKILLS_others_content_2': 'SQL Server/Postgres/SQLite。',
        'SKILLS_others_content_3': ' • Has the concept and experience of Scrum.',
        'SKILLS_others_content_4': ' • Familiar with the concept of database normalization,SQL instructions.',
        'SKILLS_others_content_5': ' • Familiar with SVN version control and Understand using Git.',
        'SKILLS_others_content_6': ' • Has more than two years of experience in database design and management.',
        'PORTFOLIO_item_title_1': 'Web：My Resume',
        'PORTFOLIO_item_description_1': 'Web design exercises,Design my resume into a web.',
        'PORTFOLIO_item_title_2': 'Web：',
        'PORTFOLIO_item_description_2': 'Web design exercises，Try using a pure front end to make a game.',
        'PORTFOLIO_item_title_3': 'C#：Data simulation generator',
        'PORTFOLIO_item_description_3': 'Dynamically generate simulation data using text structure, go to database or Websocket client.',
        'PORTFOLIO_item_title_4': 'golang：Crawler',
        'PORTFOLIO_item_description_4': 'golang exercises，Designa a simple crawler grabing exchange rate.',
        'PORTFOLIO_item_title_5': 'F2E：Developed package',
        'PORTFOLIO_item_description_5': 'Customize some suite features with JS and CSS.',
        'CONTACT_thx_info_title': 'Thank you for visiting.',
        'CONTACT_thx_info_content_1': 'Thank you for your visit. I hope you will like my design. If you have any questions or would like to cooperate with me, please feel free to contact me.',
        'CONTACT_thx_info_content_2': 'Have a good day.',
        'CONTACT_thx_info_signature': '-Kevin Lin.',
        'READ_MORE': 'Read More',
        'send_button': 'Send'
    },
    'zh-tw': {
        'Itme_HOME': '首頁',
        'Itme_PROFILE': '簡介',
        'Itme_SKILLS': '技能',
        'Itme_PORTFOLIO': '作品集',
        'Itme_CONTACT': '與我聯繫',
        'PROFILE_Hi': '嗨! 我是林建成',
        'PROFILE_Saying': '讓我們為產品做出更好的設計。',
        'PROFILE_About_title': '關於我',
        'PROFILE_Education_title': '學歷',
        'PROFILE_Experience_title': '經歷',
        'PROFILE_Education1': ' • 大葉大學資訊工程系',
        'PROFILE_AboutMe': '自從接觸了程式設計開始，我便喜歡上程式設計，即便在工作之餘，我也喜歡寫代碼。我同時學習了前端及後端的程式語言，試圖成為一名全端工程師，但我更喜歡前端設計。除了程式設計，我喜歡畫畫，甚至開始學習美術設計，我喜歡推理，不管是小說或謎題，朋友也說過我擅長邏輯推理。',
        'RESUME_Experience_1': ' • 捷普綠點擔任「實習工程師」。2015年7月-2016年6月',
        'RESUME_Experience_2': ' • 捷普綠點擔任「全端工程師」。2016年7月-2016年11月',
        'RESUME_Experience_3': ' • 國軍 Online。2016年12月-2017年3月',
        'RESUME_Experience_4': ' • 捷普綠點擔任「全端工程師」。2017年4月-至今',
        'SKILLS_frontend': '前端',
        'SKILLS_backend': '後端',
        'SKILLS_others': '其他',
        'SKILLS_frontend_content_1': 'HTML5/CSS/LESS。',
        'SKILLS_frontend_content_2': 'Javascript/JQuery/Vue.js。',
        'SKILLS_frontend_content_3': ' • 熟悉CSS、JS、JQuery，且能編寫套件；瞭解Vue.js、Less。',
        'SKILLS_frontend_content_4': ' • 熟悉設計版面切版、使用Web APIs、RWD、多語系。',
        'SKILLS_frontend_content_5': ' • 具有效能優化、使用者體驗（UX）之觀念。',
        'SKILLS_frontend_content_6': ' • 曾在綠點將MES（製造執行系統）RWD、多語系化，且效能優化（Web初始載入時間從3778毫秒降至1279毫秒）。',
        'SKILLS_frontend_content_7': ' • 擁有近三年全端開發經驗。',
        'SKILLS_backend_content_1': 'ASP.NET MVC(C#)。',
        'SKILLS_backend_content_2': 'Golang。',
        'SKILLS_backend_content_3': ' • 熟悉串接資料庫、開發Web APIs之能力。',
        'SKILLS_backend_content_4': ' • 具有物件導向、架設站台之觀念。',
        'SKILLS_backend_content_5': ' • 曾在綠點使用KEYENCE之library編寫PLC讀寫程式。',
        'SKILLS_backend_content_6': ' • 擁有近三年全端開發經驗。',
        'SKILLS_others_content_1': 'Git/SVN。',
        'SKILLS_others_content_2': 'SQL Server/Postgres/SQLite。',
        'SKILLS_others_content_3': ' • 具有Scrum之觀念和經驗。',
        'SKILLS_others_content_4': ' • 熟悉資料庫正規化、SQL指令之觀念。',
        'SKILLS_others_content_5': ' • 熟悉SVN版本控管，瞭解Git。',
        'SKILLS_others_content_6': ' • 擁有兩年以上資料庫設計、管理之經驗。',
        'PORTFOLIO_item_title_1': '網頁：我的履歷',
        'PORTFOLIO_item_description_1': '將我的履歷設計成一個網頁，順便做網頁設計練習。',
        'PORTFOLIO_item_title_2': '網頁：小瑪莉遊戲',
        'PORTFOLIO_item_description_2': '算是一個小練習，嘗試使用純前端做出一個小瑪莉遊戲。',
        'PORTFOLIO_item_title_3': 'C#：資料模擬生成程式',
        'PORTFOLIO_item_description_3': '使用文字結構動態生成模擬資料，轉至資料庫或者Websocket client。',
        'PORTFOLIO_item_title_4': 'golang：爬蟲程式',
        'PORTFOLIO_item_description_4': 'golang的練習，寫個簡單的爬蟲，爬台銀匯率存至資料庫。',
        'PORTFOLIO_item_title_5': 'F2E：自開發模組',
        'PORTFOLIO_item_description_5': '使用JS與CSS自定義一些套件功能。',
        'CONTACT_thx_info_title': '感謝您的拜訪',
        'CONTACT_thx_info_content_1': '感謝您的拜訪，希望您會喜歡我的設計，如果您有相關問題或想與我合作，都歡迎與我聯繫。',
        'CONTACT_thx_info_content_2': '祝您有愉快的一天。',
        'CONTACT_thx_info_signature': '-林建成',
        'READ_MORE': '更多資訊',
        'send_button': '傳送'
    }
};

$(function() {
    $('.translate').click(function() {
        var lang = $(this).attr('id');

        $('.lang').each(function(index, element) {
            $(this).text(arrLang[lang][$(this).attr('data-key')]);
        });
    });
});