var arrLang = {
    'en': {
        'Itme_HOME': 'HOME',
        'Itme_PROFILE': 'PROFILE',
        'Itme_SKILLS': 'SKILLS',
        'Itme_PORTFOLIO': 'PORTFOLIO',
        'Itme_CONTACT': 'CONTACT',
        'PROFILE_Hi': 'Hi!',
        'PROFILE_myName': 'I\'m Kevin Lin',
        'PROFILE_Saying': 'Let\'s make a better design for the product.',
        'PROFILE_Education_title': 'Education',
        'PROFILE_Experience_title': 'Experience',
        'PROFILE_Education1': ' • Da-Yeh University CSIE.',
        'PROFILE_Personality_1': 'Have passion to learn and programming.',
        'PROFILE_Personality_2': 'Happy to accept challenges.',
        'PROFILE_Personality_3': 'Love design and solve problems.',
        'RESUME_Experience_1': ' • Jabil Green Point(Full Stack Developer). Jul 2015-Jun 2016',
        'RESUME_Experience_2': ' • Jabil Green Point(Full Stack Developer). Jul 2016-Nov 2016',
        'RESUME_Experience_3': ' • R.O.C. Army Dec 2016-Mar 2017',
        'RESUME_Experience_4': ' • Jabil Green Point(Full Stack Developer). Apr 2017-Present',
        'SKILLS_frontend': 'Front End',
        'SKILLS_backend': 'Back End',
        'SKILLS_others': 'Others',
        'SKILLS_frontend_content_1': 'HTML5/CSS/LESS.',
        'SKILLS_frontend_content_2': 'Javascript/JQuery/Vue.js.',
        'SKILLS_frontend_content_3': ' • Has web layout cutting,connecting API,designing RWD and developing i18n skills.',
        'SKILLS_frontend_content_4': ' • Has optimization web and UX concept.',
        'SKILLS_frontend_content_5': ' • Let MES RWD,multilingual and performance optimization in the "Green Point"(Web initial load time from 3778 ms to 1279 ms).',
        'SKILLS_frontend_content_6': ' • Has nearly three years of full-end development experience.',
        'SKILLS_backend_content_1': 'ASP.NET MVC(C#).',
        'SKILLS_backend_content_2': 'Golang.',
        'SKILLS_backend_content_3': ' • Has the ability to concatenate databases and develop Web APIs.',
        'SKILLS_backend_content_4': ' • Has OOP and setting server concept.',
        'SKILLS_backend_content_5': ' • Developing PLC control program with KEYENCE library in the "Green Point".',
        'SKILLS_backend_content_6': ' • Has nearly three years of full-end development experience.',
        'SKILLS_others_content_1': 'SQL Server/Postgres/My SQL/SQLite.',
        'SKILLS_others_content_2': 'Git/SVN.',
        'SKILLS_others_content_3': ' • Has the concept and experience of Scrum.',
        'SKILLS_others_content_4': ' • Has the concept of database normalization,SQL instructions.',
        'SKILLS_others_content_5': ' • Has version control Experience.',
        'SKILLS_others_content_6': ' • Has more than two years of experience in database design and management.',
        'PORTFOLIO_item_title_1': 'Web(Golang)：My resume',
        'PORTFOLIO_item_description_1': 'As the name suggests.',
        'PORTFOLIO_item_title_2': 'Golang：Crawler program',
        'PORTFOLIO_item_description_2': 'Get the bank of Taiwan exchange rate into the database.',
        'PORTFOLIO_item_title_3': 'C#：Data generator',
        'PORTFOLIO_item_description_3': 'The simulation data is dynamically generated using the text structure and stored in the database.',
        'PORTFOLIO_item_title_4': 'Arduino：Robot car',
        'PORTFOLIO_item_description_4': 'Combine the robot with the Arduino UNO self-propelled car and write a Bluetooth controlled app operation.',
        'PORTFOLIO_item_title_5': 'Web(JSP)：Forum',
        'PORTFOLIO_item_description_5': 'The final assignments written in the student era,using JSP to simply design a discussion forum page.',
        'PORTFOLIO_item_title_6': 'Web(C#): Web optimization',
        'PORTFOLIO_item_description_6': 'MES：Optimize performance,RWD and multilingualization.',
        'PORTFOLIO_item_title_7': 'F2E：My package',
        'PORTFOLIO_item_description_7': 'Customize some suite features with JS and CSS.',
        'CONTACT_thx_info_title': 'Thank you for visiting.',
        'CONTACT_thx_info_content_1': 'There is no end to the design road. In the future,I will be more sophisticated. If you like my creation or have related questions,please feel free to contact me. Have a good  day.',
        'CONTACT_thx_info_content_2': 'Have a good day.',
        'CONTACT_thx_info_signature': '-Kevin Lin.',
    },
    'zh-tw': {
        'Itme_HOME': '首頁',
        'Itme_PROFILE': '簡介',
        'Itme_SKILLS': '技能',
        'Itme_PORTFOLIO': '作品集',
        'Itme_CONTACT': '與我聯繫',
        'PROFILE_Hi': '嗨!',
        'PROFILE_myName': '我是林建成',
        'PROFILE_Saying': '讓我們為產品做出更好的設計。',
        'PROFILE_Education_title': '學歷',
        'PROFILE_Experience_title': '經歷',
        'PROFILE_Education1': ' • 大葉大學資訊工程系',
        'PROFILE_Personality_1': '對學習和編程充滿熱情。',
        'PROFILE_Personality_2': '樂於接受挑戰。',
        'PROFILE_Personality_3': '喜愛設計以及解決問題。',
        'RESUME_Experience_1': ' • 捷普綠點擔任「實習工程師」。2015年7月-2016年6月',
        'RESUME_Experience_2': ' • 捷普綠點擔任「全端工程師」。2016年7月-2016年11月',
        'RESUME_Experience_3': ' • 國軍 Online。2016年12月-2017年3月',
        'RESUME_Experience_4': ' • 捷普綠點擔任「全端工程師」。2017年4月-至今',
        'SKILLS_frontend': '前端',
        'SKILLS_backend': '後端',
        'SKILLS_others': '其他',
        'SKILLS_frontend_content_1': 'HTML5/CSS/LESS。',
        'SKILLS_frontend_content_2': 'Javascript/JQuery/Vue.js。',
        'SKILLS_frontend_content_3': ' • 具有版面切版、串接API、設計RWD、多語系之能力。',
        'SKILLS_frontend_content_4': ' • 具有效能優化、使用者體驗（UX）之觀念。',
        'SKILLS_frontend_content_5': ' • 曾在綠點將MES（製造執行系統）RWD、多語系化，且效能優化（Web初始載入時間從3778毫秒至1279毫秒）。',
        'SKILLS_frontend_content_6': ' • 擁有近三年全端開發經驗。',
        'SKILLS_backend_content_1': 'ASP.NET MVC(C#)。',
        'SKILLS_backend_content_2': 'Golang。',
        'SKILLS_backend_content_3': ' • 具有串接資料庫、開發Web API之能力。',
        'SKILLS_backend_content_4': ' • 具有物件導向、架設站台之觀念。',
        'SKILLS_backend_content_5': ' • 曾在綠點使用KEYENCE之library編寫PLC讀寫程式。',
        'SKILLS_backend_content_6': ' • 擁有近三年全端開發經驗。',
        'SKILLS_others_content_1': 'SQL Server/Postgres/My SQL/SQLite。',
        'SKILLS_others_content_2': 'Git/SVN。',
        'SKILLS_others_content_3': ' • 具有Scrum之觀念和經驗。',
        'SKILLS_others_content_4': ' • 具有資料庫正規化、SQL指令之觀念。',
        'SKILLS_others_content_5': ' • 具有版本控管之經驗。',
        'SKILLS_others_content_6': ' • 擁有兩年以上資料庫設計、管理之經驗。',
        'PORTFOLIO_item_title_1': '網頁(Golang)：我的履歷',
        'PORTFOLIO_item_description_1': '顧名思義',
        'PORTFOLIO_item_title_2': 'Golang：爬蟲程式',
        'PORTFOLIO_item_description_2': '抓取台銀匯率存入資料庫',
        'PORTFOLIO_item_title_3': 'C#：資料模擬生成程式',
        'PORTFOLIO_item_description_3': '使用文字結構動態生成模擬資料，且存入資料庫。',
        'PORTFOLIO_item_title_4': 'Arduino：移動式機械手臂',
        'PORTFOLIO_item_description_4': '將機械手臂與Arduino UNO自走車結合，並寫一個藍芽控制的APP操作。',
        'PORTFOLIO_item_title_5': '網頁(JSP)：討論區',
        'PORTFOLIO_item_description_5': '學生時代所寫的期末作業，使用JSP簡單設計一個討論區網頁。',
        'PORTFOLIO_item_title_6': '網頁(C#)：網頁優化',
        'PORTFOLIO_item_description_6': 'MES看板：優化效能、RWD化、多語系化。',
        'PORTFOLIO_item_title_7': 'F2E：自創套件',
        'PORTFOLIO_item_description_7': '使用JS與CSS自定義一些套件功能。',
        'CONTACT_thx_info_title': '感謝您的拜訪',
        'CONTACT_thx_info_content_1': '設計的路上沒有盡頭，未來我會更加精進自己實力，如果你喜歡我的作品，或者有相關問題，都歡迎與我聯繫。',
        'CONTACT_thx_info_content_2': '祝您有愉快的一天。',
        'CONTACT_thx_info_signature': '-林建成',
    }
};

$(function() {
    $('.translate').click(function() {
        var lang = $(this).attr('id');

        $('.lang').each(function(index, element) {
            $(this).text(arrLang[lang][$(this).attr('data-key')]);
        });
    });
});