var arrLang = {
    'en': {
        'Itme_HOME': 'HOME',
        'Itme_PROFILE': 'PROFILE',
        'Itme_PROFILE_1': 'Personal photo.',
        'Itme_PROFILE_2': 'Autobiography.',
        'Itme_PROFILE_3': 'Education＆Experience.',
        'Itme_SKILLS': 'SKILLS',
        'Itme_SKILLS_1': 'Font End.',
        'Itme_SKILLS_2': 'Back End.',
        'Itme_SKILLS_3': 'Others.',
        'Itme_PORTFOLIO': 'PORTFOLIO',
        'Itme_PORTFOLIO_1': 'My resume.',
        'Itme_PORTFOLIO_2': 'A web game.',
        'Itme_PORTFOLIO_3': 'Data simulation generator.',
        'Itme_PORTFOLIO_4': 'Crawler.',
        'Itme_PORTFOLIO_5': 'Developed package.',
        'Itme_CONTACT': 'CONTACT',
        'Itme_CONTACT_1': 'Please don\'t hesitate to contact me.',
        'PROFILE_Hi': 'Hi! I\'m Kevin Lin.',
        'PROFILE_Autobiography_title': 'AUTOBIOGRAPHY',
        'PROFILE_Education_title': 'EDUCATION',
        'PROFILE_Experience_title': 'EXPERIENCE',
        'PROFILE_Education1': ' • Da-Yeh University CSIE.',
        'PROFILE_AboutMe': 'In addition to programming,I like to paint and am also starting to learn art design.I\'m a very logical person that loves solving problems,I strive to do my best when solving problems.',
        'PROFILE_Autobiography_now_title': 'PAST TO PRESENT',
        'PROFILE_Autobiography_now_1': 'My name is Kevin Lin. Ever since I was a young child I was very interested in all things computer science related. Which resulted in me deciding to study and eventually graduating at Da Ye University\'s Information Engineering Department.',
        'PROFILE_Autobiography_now_2': 'My personality is active, so I let myself work in the administrative unit and full-time internships between universities, increase my social experience and skills, and continue to improve in the internship process such as HTML, CSS, JavaScript, C#, SQL, etc. Skills, also developed some system for the company, and later became a full-time staff because of the ability to change.',        
        'PROFILE_Autobiography_now_3': 'I specialize in web design, including front-end programming (micro-art design, UI, UX), back-end programming (C#, golang), database management and design, and practical web design experience for nearly three years.',        
        'PROFILE_Autobiography_future_title': 'IN FUTURE',
        'PROFILE_Autobiography_future': 'I\'m trying to be a full stack engineer, so I\'m committed to learning the front-end and back-end programming languages.After work, I will do self-learning. I have recently started to learn Illustrator, Photoshop and other skills. In the future, I will continue to improve my self-improvement. The goal is to become a full-stack engineer before the age of 30.',
        'RESUME_Experience_1': 'Jabil Green Point(Internship web development engineer). Jul 2015-Jun 2016',
        'RESUME_Experience_1_content': 'Implement EIP web(front end,back end,database)。',
        'RESUME_Experience_2': 'Jabil Green Point(Web development engineer). Jul 2016-Nov 2016',
        'RESUME_Experience_2_content_1': 'Implement MES web UI(front end,back end,database)。',
        'RESUME_Experience_2_content_2': 'MES back control program develop.',
        'RESUME_Experience_3': 'R.O.C. Army. Dec 2016-Mar 2017',
        'RESUME_Experience_4': 'Jabil Green Point(Web development engineer). Apr 2017-Nov 2018',
        'RESUME_Experience_4_content_1': 'Implement MES RWD and Internationalization.',
        'RESUME_Experience_4_content_2': 'Implement KEYENCE PLC communication program.',
        'SKILLS_frontend': 'Front End',
        'SKILLS_backend': 'Back End',
        'SKILLS_others': 'Others',       
        'SKILLS_frontend_content_1': ' • Familiar with design layout, Web APIs, RWD, i18n, AJAX.',
        'SKILLS_frontend_content_2': ' • Has the concept of a basic user experience (UX).',
        'SKILLS_frontend_content_3': ' • Understand how to use SVG＆Bootstrap .',       
        'SKILLS_backend_content_1': 'ASP.NET MVC(C#).',
        'SKILLS_backend_content_2': 'Golang.',
        'SKILLS_backend_content_3': ' • Has the ability to concatenate databases and develop Web APIs.',
        'SKILLS_backend_content_4': ' • Has OOP and setting server concept.',
        'SKILLS_backend_content_5': ' • Developing PLC control program with KEYENCE library in the "Green Point".',
        'SKILLS_backend_content_6': ' • Has nearly three years of full-end development experience.',        
        'SKILLS_others_content_1': ' • Has the concept and experience of Scrum.',
        'SKILLS_others_content_2': ' • Learning Illustrator, Photoshop now.',
        'PORTFOLIO_item_title_1': 'Web：My Resume',
        'PORTFOLIO_item_description_1': 'Web design exercises,Design my resume into a web.',
        'PORTFOLIO_item_title_2': 'Web：',
        'PORTFOLIO_item_description_2': 'Web design exercises，Try using a pure front end to make a game.',
        'PORTFOLIO_item_title_3': 'C#：Data simulation generator',
        'PORTFOLIO_item_description_3': 'Dynamically generate simulation data using text structure, go to database or Websocket client.',
        'PORTFOLIO_item_title_4': 'golang：Crawler',
        'PORTFOLIO_item_description_4': 'golang exercises，Designa a simple crawler grabing exchange rate.',
        'PORTFOLIO_item_title_5': 'F2E：Developed package',
        'PORTFOLIO_item_description_5': 'Customize some suite features with JS and CSS.',
        'CONTACT_thx_info_title': 'Thank you for visiting.',
        'CONTACT_thx_info_content_1': 'Thank you for your visit. If you have any questions or would like to cooperate with me, please feel free to contact me.',
        'CONTACT_thx_info_content_2': 'Have a good day.',
        'CONTACT_thx_info_signature': '-Kevin Lin.',
        'READ_MORE': 'Read More',
        'send_button': 'Send'
    },
    'zh-tw': {
        'Itme_HOME': '首頁',
        'Itme_PROFILE': '簡介',
        'Itme_PROFILE_1': '頭像',
        'Itme_PROFILE_2': '自傳',
        'Itme_PROFILE_3': '學經歷',
        'Itme_SKILLS': '技能',
        'Itme_SKILLS_1': '前端技能',
        'Itme_SKILLS_2': '後端技能',
        'Itme_SKILLS_3': '其他技能',
        'Itme_PORTFOLIO': '作品集',
        'Itme_PORTFOLIO_1': '履歷',
        'Itme_PORTFOLIO_2': '一個網頁遊戲',
        'Itme_PORTFOLIO_3': '資料生成模擬程式',
        'Itme_PORTFOLIO_4': '爬蟲程式',
        'Itme_PORTFOLIO_5': '自開發模組',
        'Itme_CONTACT': '與我聯繫',
        'Itme_CONTACT_1': '歡迎使用郵件與我聯繫',
        'PROFILE_Hi': '嗨! 我是林建成',
        'PROFILE_Autobiography_title': '自傳',
        'PROFILE_Education_title': '學歷',
        'PROFILE_Experience_title': '經歷',
        'PROFILE_Education1': ' • 大葉大學資訊工程學士',
        'PROFILE_AboutMe': '除了程式設計，我喜歡畫畫，也開始學習美術設計，我是一個合乎邏輯的人，喜歡去解決問題，也全力以赴在面對問題。',
        'PROFILE_Autobiography_now_title': '以往至今',
        'PROFILE_Autobiography_now_1': '我是林建成，大學畢業於大葉大學資訊工程系，因從小對電腦方面等資訊有極大的興趣，進而使我選擇了資訊這條路。',
        'PROFILE_Autobiography_now_2': '我個性主動積極，所以在大學之間我讓自己從事行政單位的工讀以及企業的全職實習，增加我的社會經驗以及技能專長，在實習過程中不斷精進如HTML、CSS、JavaScript、C#、SQL等技能，也替公司開發了系統，後來因為能力適任轉而成為正職人員。',        
        'PROFILE_Autobiography_now_3': '我擅長領域為網頁設計，包含前端程式設計(微美術設計、UI、UX)、後端程式開發(C#、golang)、資料庫管理與設計，實質網頁設計經驗近三年。 ',        
        'PROFILE_Autobiography_future_title': '未來',
        'PROFILE_Autobiography_future': '我試圖成為一名全端工程師，致力學習前端以及後端的程式語言，下班後我會去做自主學習，近期開始學習Illustrator、Photoshop等技能，在未來裡我會不斷地精進自我的實力，目標在三十歲前能成為一個全端工程師。',
        'RESUME_Experience_1': '捷普綠點擔任「網頁開發工程師(實習)」。2015年7月-2016年6月',
        'RESUME_Experience_1_content': '實作企業入口網站(前端、後端、資料庫設計規劃)。',
        'RESUME_Experience_2': '捷普綠點擔任「網頁開發工程師」。2016年7月-2016年11月',
        'RESUME_Experience_2_content_1': '實作MES中網頁介面(前端、後端、資料庫設計規劃)。',
        'RESUME_Experience_2_content_2': 'MES中底層收集程式開發。',
        'RESUME_Experience_3': '國軍 Online。2016年12月-2017年3月',
        'RESUME_Experience_4': '捷普綠點擔任「網頁開發工程師」。2017年4月-2018年11月',
        'RESUME_Experience_4_content_1': '實作MES網頁介面響應式化、多語系化。',
        'RESUME_Experience_4_content_2': '實作KEYENCE PLC讀寫程式。',
        'SKILLS_frontend': '前端',
        'SKILLS_backend': '後端',
        'SKILLS_others': '其他',
        'SKILLS_frontend_content_1': ' • 熟悉設計切版、Web APIs、RWD、多語系、AJAX。',
        'SKILLS_frontend_content_2': ' • 具有基本使用者體驗（UX）之觀念。',
        'SKILLS_frontend_content_3': ' • 懂如何使用SVG＆Bootstrap。',
        'SKILLS_backend_content_1': ' • 熟悉串接資料庫、開發Web APIs之能力。',
        'SKILLS_backend_content_2': ' • 具有物件導向、架設站台之觀念。',
        'SKILLS_others_content_1': ' • 具有Scrum之觀念和經驗。',
        'SKILLS_others_content_2': ' • 正在學習Illustrator、Photoshop。',
        'PORTFOLIO_item_title_1': '網頁：我的履歷',
        'PORTFOLIO_item_description_1': '將我的履歷設計成一個網頁，順便做網頁設計練習。',
        'PORTFOLIO_item_title_2': '網頁：小瑪莉遊戲',
        'PORTFOLIO_item_description_2': '算是一個小練習，嘗試使用純前端做出一個小瑪莉遊戲。',
        'PORTFOLIO_item_title_3': 'C#：資料模擬生成程式',
        'PORTFOLIO_item_description_3': '使用文字結構動態生成模擬資料，轉至資料庫或者Websocket client。',
        'PORTFOLIO_item_title_4': 'golang：爬蟲程式',
        'PORTFOLIO_item_description_4': 'golang的練習，寫個簡單的爬蟲，爬台銀匯率存至資料庫。',
        'PORTFOLIO_item_title_5': 'F2E：自開發模組',
        'PORTFOLIO_item_description_5': '使用JS與CSS自定義一些套件功能。',
        'CONTACT_thx_info_title': '感謝您的拜訪',
        'CONTACT_thx_info_content_1': '感謝您的拜訪，希望如果您有相關問題或想與我合作，都歡迎與我聯繫。',
        'CONTACT_thx_info_content_2': '祝您有愉快的一天。',
        'CONTACT_thx_info_signature': '-林建成',
        'READ_MORE': '更多資訊',
        'send_button': '傳送'
    }
};

$(function() {
    $('.translate').click(function() {
        var lang = $(this).attr('id');

        $('.lang').each(function(index, element) {
            $(this).text(arrLang[lang][$(this).attr('data-key')]);
        });
    });
});